// Generated by ntl build --embed
// Embedded modules: ntl:cache, ntl:logger

const __ntl_embed_cache__ = (function() {
  const _ntl_mod__data_data_com_termux_files_home_workspace_ntl_lang_modules_cache_js = (function() {
    const module = { exports: {} };
    const exports = module.exports;
    const __filename = "/data/data/com.termux/files/home/workspace/ntl-lang/modules/cache.js";
    const __dirname  = "/data/data/com.termux/files/home/workspace/ntl-lang/modules";
    class CacheEntry {
      constructor(key, value, ttl) {
        this.key       = key;
        this.value     = value;
        this.ttl       = ttl || 0;
        this.expires   = ttl ? Date.now() + ttl : 0;
        this.hits      = 0;
        this.createdAt = Date.now();
        this.updatedAt = Date.now();
        this.prev      = null;
        this.next      = null;
      }
      isExpired() { return this.expires > 0 && Date.now() > this.expires; }
      touch()     { this.hits++; return this; }
      refresh(ttl) {
        this.expires   = ttl ? Date.now() + ttl : this.expires;
        this.updatedAt = Date.now();
        return this;
      }
    }
    
    class Cache {
      constructor(opts) {
        opts           = opts || {};
        this._max      = opts.maxSize    || opts.max    || 1000;
        this._ttl      = opts.ttl        || 0;
        this._map      = new Map();
        this._head     = null;
        this._tail     = null;
        this._hits     = 0;
        this._misses   = 0;
        this._evictions = 0;
        this._onEvict  = opts.onEvict   || null;
        this._onExpire = opts.onExpire  || null;
    
        if (opts.checkInterval !== false) {
          const interval = opts.checkInterval || 60000;
          this._timer = setInterval(() => this._evictExpired(), interval);
          if (this._timer.unref) this._timer.unref();
        }
      }
    
      get(key) {
        const entry = this._map.get(key);
        if (!entry)         { this._misses++; return undefined; }
        if (entry.isExpired()) {
          this._delete(entry);
          this._misses++;
          if (this._onExpire) this._onExpire(key, entry.value);
          return undefined;
        }
        this._hits++;
        entry.touch();
        this._moveToFront(entry);
        return entry.value;
      }
    
      set(key, value, ttl) {
        const existingEntry = this._map.get(key);
        if (existingEntry) {
          existingEntry.value   = value;
          existingEntry.ttl     = ttl !== undefined ? ttl : this._ttl;
          existingEntry.expires = existingEntry.ttl ? Date.now() + existingEntry.ttl : 0;
          existingEntry.updatedAt = Date.now();
          this._moveToFront(existingEntry);
          return this;
        }
        const entry = new CacheEntry(key, value, ttl !== undefined ? ttl : this._ttl);
        this._map.set(key, entry);
        this._addToFront(entry);
        if (this._map.size > this._max) this._evictLRU();
        return this;
      }
    
      has(key) {
        const entry = this._map.get(key);
        if (!entry) return false;
        if (entry.isExpired()) { this._delete(entry); return false; }
        return true;
      }
    
      delete(key) {
        const entry = this._map.get(key);
        if (!entry) return false;
        this._delete(entry);
        return true;
      }
    
      clear() {
        this._map.clear();
        this._head = null;
        this._tail = null;
      }
    
      get size() { return this._map.size; }
    
      keys()   { return [...this._map.keys()]; }
      values() { return [...this._map.values()].map(e => e.value); }
      entries(){ return [...this._map.entries()].map(([k, e]) => [k, e.value]); }
    
      getEntry(key) { return this._map.get(key); }
    
      mget(keys) { return keys.map(k => this.get(k)); }
    
      mset(entries, ttl) {
        for (const [k, v] of entries) this.set(k, v, ttl);
        return this;
      }
    
      getOrSet(key, fn, ttl) {
        const v = this.get(key);
        if (v !== undefined) return v;
        const result = fn(key);
        if (result && typeof result.then === 'function') {
          return result.then(val => { this.set(key, val, ttl); return val; });
        }
        this.set(key, result, ttl);
        return result;
      }
    
      ttl(key) {
        const entry = this._map.get(key);
        if (!entry || entry.isExpired()) return -2;
        if (!entry.expires) return -1;
        return Math.max(0, entry.expires - Date.now());
      }
    
      expire(key, ttl) {
        const entry = this._map.get(key);
        if (!entry) return false;
        entry.refresh(ttl);
        return true;
      }
    
      rename(oldKey, newKey) {
        const entry = this._map.get(oldKey);
        if (!entry) return false;
        this._map.delete(oldKey);
        entry.key = newKey;
        this._map.set(newKey, entry);
        return true;
      }
    
      namespace(prefix) {
        const sep = ':';
        return {
          get:    (k)       => this.get(prefix + sep + k),
          set:    (k, v, t) => this.set(prefix + sep + k, v, t),
          has:    (k)       => this.has(prefix + sep + k),
          delete: (k)       => this.delete(prefix + sep + k),
          clear:  ()        => { for (const k of this._map.keys()) if (k.startsWith(prefix + sep)) this.delete(k.slice(prefix.length + 1)); },
          keys:   ()        => this.keys().filter(k => k.startsWith(prefix + sep)).map(k => k.slice(prefix.length + 1)),
          getOrSet: (k, fn, t) => this.getOrSet(prefix + sep + k, fn, t),
        };
      }
    
      wrap(fn, keyFn, ttl) {
        return async (...args) => {
          const key    = keyFn ? keyFn(...args) : JSON.stringify(args);
          const cached = this.get(key);
          if (cached !== undefined) return cached;
          const result = await fn(...args);
          this.set(key, result, ttl);
          return result;
        };
      }
    
      stats() {
        const total = this._hits + this._misses;
        return {
          size:      this._map.size,
          maxSize:   this._max,
          hits:      this._hits,
          misses:    this._misses,
          hitRate:   total ? (this._hits / total).toFixed(3) : '0.000',
          evictions: this._evictions,
        };
      }
    
      _addToFront(entry) {
        entry.next = this._head;
        entry.prev = null;
        if (this._head) this._head.prev = entry;
        this._head = entry;
        if (!this._tail) this._tail = entry;
      }
    
      _moveToFront(entry) {
        if (entry === this._head) return;
        this._removeFromList(entry);
        this._addToFront(entry);
      }
    
      _removeFromList(entry) {
        if (entry.prev) entry.prev.next = entry.next;
        if (entry.next) entry.next.prev = entry.prev;
        if (entry === this._head) this._head = entry.next;
        if (entry === this._tail) this._tail = entry.prev;
        entry.prev = entry.next = null;
      }
    
      _delete(entry) {
        this._removeFromList(entry);
        this._map.delete(entry.key);
        if (this._onEvict) this._onEvict(entry.key, entry.value);
      }
    
      _evictLRU() {
        if (!this._tail) return;
        const evicted = this._tail;
        this._delete(evicted);
        this._evictions++;
      }
    
      _evictExpired() {
        const now = Date.now();
        for (const entry of this._map.values()) {
          if (entry.expires > 0 && now > entry.expires) {
            this._delete(entry);
            if (this._onExpire) this._onExpire(entry.key, entry.value);
          }
        }
      }
    
      destroy() {
        if (this._timer) { clearInterval(this._timer); this._timer = null; }
        this.clear();
      }
    }
    
    module.exports = { Cache };
    return module.exports;
  })();
  return _ntl_mod__data_data_com_termux_files_home_workspace_ntl_lang_modules_cache_js;
})();
const __ntl_embed_logger__ = (function() {
  const _ntl_mod__data_data_com_termux_files_home_workspace_ntl_lang_modules_logger_js = (function() {
    const module = { exports: {} };
    const exports = module.exports;
    const __filename = "/data/data/com.termux/files/home/workspace/ntl-lang/modules/logger.js";
    const __dirname  = "/data/data/com.termux/files/home/workspace/ntl-lang/modules";
    const fs     = require('fs');
    const path   = require('path');
    const os     = require('os');
    const crypto = require('crypto');
    
    const fs     = require('fs');
    
    const path   = require('path');
    
    const LEVELS  = { trace: 10, debug: 20, info: 30, warn: 40, error: 50, fatal: 60, silent: Infinity };
    
    const COLORS  = {
      trace: '\x1b[37m',  debug: '\x1b[36m', info:  '\x1b[32m',
      warn:  '\x1b[33m',  error: '\x1b[31m', fatal: '\x1b[35m',
    };
    
    const RESET = '\x1b[0m';
    
    const GRAY  = '\x1b[90m';
    
    const BOLD  = '\x1b[1m';
    
    const DIM   = '\x1b[2m';
    
    function levelName(n) {
      return Object.entries(LEVELS).find(([, v]) => v === n)?.[0] || String(n);
    }
    
    function safeStringify(obj, indent) {
      const seen = new WeakSet();
      return JSON.stringify(obj, (k, v) => {
        if (typeof v === 'object' && v !== null) {
          if (seen.has(v)) return '[Circular]';
          seen.add(v);
        }
        if (typeof v === 'bigint') return v.toString();
        if (v instanceof Error) return { message: v.message, name: v.name, stack: v.stack };
        return v;
      }, indent);
    }
    
    class Logger {
      constructor(opts) {
        opts           = opts || {};
        this._name     = opts.name      || null;
        this._level    = LEVELS[opts.level] ?? LEVELS.info;
        this._pretty   = opts.pretty    !== false;
        this._useColor = opts.color     !== false && process.stdout.isTTY;
        this._filePath = opts.filePath  || null;
        this._redact   = opts.redact    || [];
        this._parent   = opts._parent   || null;
        this._ctx      = opts.context   || {};
        this._streams  = [];
        this._fileStream = null;
    
        if (this._filePath) {
          fs.mkdirSync(path.dirname(path.resolve(this._filePath)), { recursive: true });
          this._fileStream = fs.createWriteStream(this._filePath, { flags: 'a' });
        }
      }
    
      _write(level, msg, data) {
        if (level < this._level) return;
        const name_  = levelName(level);
        const ts     = new Date().toISOString();
        const merged = Object.assign({}, this._ctx, data || {});
        if (this._parent) Object.assign(merged, this._parent._ctx);
    
        if (this._redact.length) {
          for (const key of this._redact) {
            delete merged[key];
            if (merged.err) delete merged.err[key];
          }
        }
    
        if (this._pretty) {
          const color = this._useColor ? (COLORS[name_] || RESET) : '';
          const end   = this._useColor ? RESET : '';
          const gray  = this._useColor ? GRAY  : '';
          const bold  = this._useColor ? BOLD  : '';
          const dim   = this._useColor ? DIM   : '';
    
          let line = `${gray}${ts}${end}  ${bold}${color}${name_.toUpperCase().padEnd(5)}${end}`;
          if (this._name) line += `  ${dim}${this._name}${end}`;
          if (msg)        line += `  ${msg}`;
    
          const extra = Object.assign({}, merged);
          if (extra.err && extra.err.stack) {
            line += '\n' + gray + extra.err.stack + end;
            delete extra.err;
          }
          const keys = Object.keys(extra);
          if (keys.length) {
            if (keys.length <= 3 && keys.every(k => typeof extra[k] !== 'object' || extra[k] === null)) {
              line += '  ' + gray + keys.map(k => `${k}=${JSON.stringify(extra[k])}`).join(' ') + end;
            } else {
              line += '\n' + gray + safeStringify(extra, 2).split('\n').map(l => '  ' + l).join('\n') + end;
            }
          }
    
          process.stdout.write(line + '\n');
        } else {
          const log = Object.assign({ time: ts, level: level, name: this._name, msg }, merged);
          const line = safeStringify(log) + '\n';
          process.stdout.write(line);
          if (this._fileStream) this._fileStream.write(line);
        }
      }
    
      trace(msg, data)  { this._write(LEVELS.trace, msg, data); }
      debug(msg, data)  { this._write(LEVELS.debug, msg, data); }
      info(msg, data)   { this._write(LEVELS.info,  msg, data); }
      warn(msg, data)   { this._write(LEVELS.warn,  msg, data); }
      error(msg, data)  { this._write(LEVELS.error, msg, data); }
      fatal(msg, data)  { this._write(LEVELS.fatal, msg, data); process.nextTick(() => process.exit(1)); }
    
      log(level, msg, data) {
        const lvl = typeof level === 'string' ? (LEVELS[level] ?? LEVELS.info) : level;
        this._write(lvl, msg, data);
      }
    
      child(ctx) {
        return new Logger({
          name:     this._name,
          level:    levelName(this._level),
          pretty:   this._pretty,
          color:    this._useColor,
          filePath: this._filePath,
          redact:   this._redact,
          context:  Object.assign({}, this._ctx, ctx),
          _parent:  this,
        });
      }
    
      withContext(ctx) { return this.child(ctx); }
    
      setLevel(level) {
        const n = typeof level === 'string' ? LEVELS[level] : level;
        if (n !== undefined) this._level = n;
        return this;
      }
    
      get level() { return levelName(this._level); }
    
      addStream(fn) { this._streams.push(fn); return this; }
    
      startTimer(label) {
        const start = Date.now();
        return {
          done:  (msg, data) => this.info(msg || label, Object.assign({ duration_ms: Date.now() - start }, data)),
          error: (msg, data) => this.error(msg || label, Object.assign({ duration_ms: Date.now() - start }, data)),
        };
      }
    
      close() {
        if (this._fileStream) { this._fileStream.end(); this._fileStream = null; }
      }
    }
    
    module.exports = { Logger };
    return module.exports;
  })();
  return _ntl_mod__data_data_com_termux_files_home_workspace_ntl_lang_modules_logger_js;
})();

const { Cache } = __ntl_embed_cache__;

const { Logger } = __ntl_embed_logger__;


const log_ = new Logger({ level: "info", prefix: "App" });
const store = new Cache({ maxSize: 100, ttl: 5000 });
function expensiveCompute(key) {
  log_.info(`Computing value for: ${key}`);
  return `result_for_${key}_at_${Date.now()}`;
}
function getOrCompute(key) {
  const cached = store.get(key);
  if (cached !== null && cached !== undefined) {
    log_.debug(`Cache hit:  ${key}`);
    return cached;
  }
  const value = expensiveCompute(key);
  store.set(key, value);
  return value;
}
log_.info("Starting cache demo");
const r1 = getOrCompute("user:42");
const r2 = getOrCompute("user:42");
const r3 = getOrCompute("post:7");
const r4 = getOrCompute("user:42");
log_.info(`Same result r1===r2: ${r1 === r2}`);
log_.info(`Different  r1===r3: ${r1 === r3}`);
log_.info(`Same again r1===r4: ${r1 === r4}`);
log_.info(`Cache size: ${store.size}`);
store.delete("user:42");
log_.info(`After delete, size: ${store.size}`);
const r5 = getOrCompute("user:42");
log_.info(`r1===r5 (recomputed): ${r1 === r5}`);
