'use strict';

const { ArchCompiler, detectCurrentArch } = require('../jit/ArchTargets');

class WasmTypeMapper {
  static fromNTL(type) {
    const map = {
      'number': 'f64', 'int': 'i32', 'float': 'f64', 'bool': 'i32',
      'string': 'i32', 'void': null, 'any': 'i32', 'i32': 'i32',
      'i64': 'i64', 'f32': 'f32', 'f64': 'f64',
    };
    return map[type] || 'i32';
  }
}

class WatGenerator {
  constructor(arch) {
    this.arch    = new ArchCompiler(arch || detectCurrentArch());
    this.funcs   = [];
    this.imports = [];
    this.globals = [];
    this.exports = [];
    this.strings = new Map();
    this.strPtr  = 1024;
  }

  internString(s) {
    if (this.strings.has(s)) return this.strings.get(s);
    const ptr = this.strPtr;
    const encoded = Buffer.from(s, 'utf-8');
    this.strings.set(s, { ptr, len: encoded.length, bytes: encoded });
    this.strPtr += encoded.length + 1;
    return { ptr, len: encoded.length };
  }

  addImport(module, name, sig) {
    this.imports.push({ module, name, sig });
  }

  addGlobal(name, type, mutable, init) {
    this.globals.push({ name, type, mutable, init: init !== undefined ? init : 0 });
  }

  genLiteral(value, type) {
    if (type === 'f64' || typeof value === 'number' && !Number.isInteger(value)) {
      return `(f64.const ${value})`;
    }
    if (type === 'i64') return `(i64.const ${value})`;
    if (type === 'f32') return `(f32.const ${value})`;
    return `(i32.const ${value})`;
  }

  genBinaryOp(op, type) {
    const t = type || 'f64';
    const ops = {
      '+': `${t}.add`, '-': `${t}.sub`, '*': `${t}.mul`,
      '/': t.startsWith('i') ? `${t}.div_s` : `${t}.div`,
      '%': `${t}.rem_s`, '**': null,
      '&&': 'i32.and', '||': 'i32.or',
      '==': t.startsWith('f') ? `${t}.eq` : `${t}.eq`,
      '!=': t.startsWith('f') ? `${t}.ne` : `${t}.ne`,
      '<':  t.startsWith('f') ? `${t}.lt` : `${t}.lt_s`,
      '>':  t.startsWith('f') ? `${t}.gt` : `${t}.gt_s`,
      '<=': t.startsWith('f') ? `${t}.le` : `${t}.le_s`,
      '>=': t.startsWith('f') ? `${t}.ge` : `${t}.ge_s`,
    };
    return ops[op] || `${t}.add`;
  }

  genASTNode(node, types) {
    if (!node) return '';
    types = types || {};

    switch (node.type) {
      case 'Literal': {
        const v = node.value;
        if (typeof v === 'number') return Number.isInteger(v) ? `(i32.const ${v})` : `(f64.const ${v})`;
        if (typeof v === 'boolean') return `(i32.const ${v ? 1 : 0})`;
        if (typeof v === 'string')  {
          const { ptr, len } = this.internString(v);
          return `(i32.const ${ptr})  ;; string "${v.slice(0, 20)}"`;
        }
        return `(i32.const 0)`;
      }
      case 'Identifier': {
        return `(local.get $${node.name})`;
      }
      case 'BinaryExpr': {
        const lhs = this.genASTNode(node.left, types);
        const rhs = this.genASTNode(node.right, types);
        const type = types[node.left && node.left.name] || 'f64';
        const op = this.genBinaryOp(node.op, type);
        return `(${op} ${lhs} ${rhs})`;
      }
      case 'UnaryExpr': {
        const operand = this.genASTNode(node.operand || node.arg, types);
        if (node.op === '-') return `(f64.neg ${operand})`;
        if (node.op === '!') return `(i32.eqz ${operand})`;
        return operand;
      }
      case 'ReturnStmt': {
        if (!node.value) return '';
        return this.genASTNode(node.value, types);
      }
      default:
        return `(nop) ;; unsupported: ${node.type}`;
    }
  }

  compileFunction(fnDecl) {
    const name    = fnDecl.name || 'anonymous';
    const params  = (fnDecl.params || []).map(p => ({
      name: p.name,
      type: WasmTypeMapper.fromNTL(p.typeAnn ? p.typeAnn.name : 'any')
    }));
    const retType = fnDecl.returnType ? WasmTypeMapper.fromNTL(fnDecl.returnType.name) : 'f64';
    const types   = {};
    for (const p of params) types[p.name] = p.type;

    const bodyStmts = (fnDecl.body && fnDecl.body.body) ? fnDecl.body.body : [];
    const bodyWAT = bodyStmts.map(stmt => this.genASTNode(stmt, types)).filter(Boolean).join('\n    ');

    const paramStr  = params.map(p => `(param $${p.name} ${p.type})`).join(' ');
    const resultStr = retType ? `(result ${retType})` : '';

    return [
      `  (func $${name} (export "${name}") ${paramStr} ${resultStr}`,
      bodyWAT ? '    ' + bodyWAT : '    (unreachable)',
      `  )`,
    ].join('\n');
  }

  generateDataSection() {
    if (!this.strings.size) return '';
    const segments = [];
    for (const [s, { ptr, bytes }] of this.strings) {
      const escaped = [...bytes].map(b => `\\${b.toString(16).padStart(2, '0')}`).join('');
      segments.push(`  (data (i32.const ${ptr}) "${escaped}") ;; "${s.slice(0, 30)}"`);
    }
    return segments.join('\n') + '\n';
  }

  build(ast) {
    const lines = [];
    lines.push(`;; NTL WebAssembly Module`);
    lines.push(`;; Target: ${this.arch.target.name}`);
    lines.push(`;; Generated by NTL v3.0`);
    lines.push(``);
    lines.push(`(module`);
    lines.push(`  (memory (export "memory") 16 1000)`);
    lines.push(``);

    lines.push(`  (import "ntl" "print_i32" (func $print_i32 (param i32)))`);
    lines.push(`  (import "ntl" "print_f64" (func $print_f64 (param f64)))`);
    lines.push(`  (import "ntl" "print_str" (func $print_str (param i32 i32)))`);
    lines.push(``);

    lines.push(`  (global $heap_ptr (mut i32) (i32.const 65536))`);
    lines.push(``);

    lines.push(`  (func $malloc (export "malloc") (param $size i32) (result i32)`);
    lines.push(`    (local $ptr i32)`);
    lines.push(`    (local.set $ptr (global.get $heap_ptr))`);
    lines.push(`    (global.set $heap_ptr (i32.add (global.get $heap_ptr) (local.get $size)))`);
    lines.push(`    (local.get $ptr)`);
    lines.push(`  )`);
    lines.push(``);

    if (ast && ast.body) {
      for (const node of ast.body) {
        if (node && node.type === 'FnDecl') {
          lines.push(this.compileFunction(node));
          lines.push('');
        }
      }
    }

    const dataSection = this.generateDataSection();
    if (dataSection) lines.push(dataSection);

    lines.push(`)`);
    return lines.join('\n');
  }
}

class WasmRuntime {
  constructor() {
    this.modules = new Map();
    this.memory  = null;
  }

  createImports(opts) {
    opts = opts || {};
    const mem = new WebAssembly.Memory({ initial: 16, maximum: 1000 });
    this.memory = mem;
    const view = () => new Uint8Array(mem.buffer);

    const readStr = (ptr, len) => {
      const buf = view().slice(ptr, ptr + len);
      return Buffer.from(buf).toString('utf-8');
    };

    return {
      ntl: {
        print_i32: (v) => process.stdout.write(String(v) + '\n'),
        print_f64: (v) => process.stdout.write(String(v) + '\n'),
        print_str: (ptr, len) => process.stdout.write(readStr(ptr, len) + '\n'),
        abort: (msg, file, line, col) => { throw new Error(`WASM abort at ${file}:${line}:${col}`); },
        ...((opts.imports && opts.imports.ntl) || {})
      },
      env: {
        memory: mem,
        ...((opts.imports && opts.imports.env) || {})
      }
    };
  }

  async instantiate(wasmBytes, opts) {
    const imports = this.createImports(opts);
    const { instance, module: mod } = await WebAssembly.instantiate(wasmBytes, imports);
    const key = opts && opts.name ? opts.name : 'module_' + Date.now();
    this.modules.set(key, { instance, module: mod });
    return instance.exports;
  }

  async instantiateBuffer(buffer, opts) {
    if (buffer instanceof Buffer) buffer = buffer.buffer.slice(buffer.byteOffset, buffer.byteOffset + buffer.byteLength);
    return this.instantiate(buffer, opts);
  }
}

class WasmCompiler {
  constructor(opts) {
    this.opts    = Object.assign({ arch: detectCurrentArch(), optimize: true }, opts || {});
    this.runtime = new WasmRuntime();
  }

  generateWAT(ast, opts) {
    const gen = new WatGenerator(opts && opts.arch ? opts.arch : this.opts.arch);
    return gen.build(ast);
  }

  async compileToWasm(ast, opts) {
    const wat = this.generateWAT(ast, opts);

    try {
      const { execSync } = require('child_process');
      const fs = require('fs');
      const os = require('os');
      const tmp = require('path').join(os.tmpdir(), 'ntl_' + Date.now() + '.wat');
      fs.writeFileSync(tmp, wat);
      const wasmPath = tmp.replace('.wat', '.wasm');
      execSync(`wat2wasm "${tmp}" -o "${wasmPath}" 2>&1`, { timeout: 10000 });
      const bytes = fs.readFileSync(wasmPath);
      fs.unlinkSync(tmp);
      fs.unlinkSync(wasmPath);
      return { success: true, wat, bytes };
    } catch (e) {
      return { success: false, wat, error: 'wat2wasm not available: ' + e.message + '\nWAT source generated successfully.' };
    }
  }

  async run(ast, opts) {
    const result = await this.compileToWasm(ast, opts);
    if (!result.success || !result.bytes) {
      return { success: false, error: result.error, wat: result.wat };
    }
    try {
      const exports = await this.runtime.instantiateBuffer(result.bytes, opts);
      return { success: true, exports, wat: result.wat };
    } catch (e) {
      return { success: false, error: e.message, wat: result.wat };
    }
  }
}

module.exports = { WasmCompiler, WasmRuntime, WatGenerator, WasmTypeMapper };
