// Generated by NTL-lang compiler — do not edit manually.
// Run: ntl build examples/06_multi_file/main.ntl --out examples/06_multi_file/main.js
//
// This file is the pre-compiled output of main.ntl using embedded local modules.
// It is fully portable (no hardcoded paths) and runs anywhere Node.js 18+ is installed.
//
//   node examples/06_multi_file/main.js

'use strict';

const math = (function() {
  const module = { exports: {} };
  const exports = module.exports;

  function add(a, b) { return a + b; }
  function subtract(a, b) { return a - b; }
  function multiply(a, b) { return a * b; }
  function divide(a, b) {
    if (!(b !== 0)) { return null; }
    return a / b;
  }
  function power(base, exp) { return Math.pow(base, exp); }
  function clamp(value, minVal, maxVal) {
    if (value < minVal) { return minVal; }
    if (value > maxVal) { return maxVal; }
    return value;
  }

  module.exports.add      = add;
  module.exports.subtract = subtract;
  module.exports.multiply = multiply;
  module.exports.divide   = divide;
  module.exports.power    = power;
  module.exports.clamp    = clamp;

  return module.exports;
})();

const strings = (function() {
  const module = { exports: {} };
  const exports = module.exports;

  function capitalize(str) {
    if (!(str.length > 0)) { return str; }
    return str[0].toUpperCase() + str.slice(1).toLowerCase();
  }
  function titleCase(str) {
    return str.split(' ').map(w => capitalize(w)).join(' ');
  }
  function truncate(str, maxLen, suffix) {
    const end = suffix || '...';
    if (!(str.length > maxLen)) { return str; }
    return str.slice(0, maxLen - end.length) + end;
  }
  function slugify(str) {
    return str.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
  }
  function countWords(str) {
    return str.trim().split(/\s+/).filter(w => w.length > 0).length;
  }

  module.exports.capitalize = capitalize;
  module.exports.titleCase  = titleCase;
  module.exports.truncate   = truncate;
  module.exports.slugify    = slugify;
  module.exports.countWords = countWords;

  return module.exports;
})();

console.log('=== Math ===');
console.log('add(3, 4)          =', math.add(3, 4));
console.log('subtract(10, 3)    =', math.subtract(10, 3));
console.log('multiply(6, 7)     =', math.multiply(6, 7));
console.log('divide(15, 3)      =', math.divide(15, 3));
console.log('divide(5, 0)       =', math.divide(5, 0));
console.log('power(2, 10)       =', math.power(2, 10));
console.log('clamp(150, 0, 100) =', math.clamp(150, 0, 100));

console.log('');
console.log('=== Strings ===');
console.log(strings.capitalize('hello world'));
console.log(strings.titleCase('the quick brown fox'));
console.log(strings.truncate('This is a very long sentence that needs trimming', 25));
console.log(strings.slugify('Hello World! This is NTL-lang 2026'));
console.log('Word count:', strings.countWords('The quick brown fox jumps over the lazy dog'));
