'use strict';

const ARCH_TARGETS = {
  'x86_64':   { name: 'x86-64 (amd64)',         bits: 64, family: 'x86',  platform: 'desktop', wasmTarget: 'x86_64-unknown-linux-gnu'  },
  'x86_32':   { name: 'x86-32 (ia32)',           bits: 32, family: 'x86',  platform: 'desktop', wasmTarget: 'i686-unknown-linux-gnu'    },
  'arm64':    { name: 'ARM64 (aarch64)',          bits: 64, family: 'arm',  platform: 'mobile',  wasmTarget: 'aarch64-unknown-linux-gnu' },
  'arm32':    { name: 'ARM32 (armv7)',            bits: 32, family: 'arm',  platform: 'mobile',  wasmTarget: 'armv7-unknown-linux-gnueabihf' },
  'wasm32':   { name: 'WebAssembly (wasm32)',     bits: 32, family: 'wasm', platform: 'web',     wasmTarget: 'wasm32-unknown-unknown'   },
  'wasm64':   { name: 'WebAssembly 64-bit',       bits: 64, family: 'wasm', platform: 'web',     wasmTarget: 'wasm64-unknown-unknown'   },
  'riscv64':  { name: 'RISC-V 64-bit',           bits: 64, family: 'riscv',platform: 'server',  wasmTarget: 'riscv64gc-unknown-linux-gnu' },
  'android-arm64': { name: 'Android ARM64',      bits: 64, family: 'arm',  platform: 'android', wasmTarget: 'aarch64-linux-android'    },
  'android-arm32': { name: 'Android ARM32',      bits: 32, family: 'arm',  platform: 'android', wasmTarget: 'armv7-linux-androideabi'  },
  'ios-arm64':     { name: 'iOS ARM64',           bits: 64, family: 'arm',  platform: 'ios',     wasmTarget: 'aarch64-apple-ios'        },
  'macos-x86_64':  { name: 'macOS Intel',         bits: 64, family: 'x86',  platform: 'macos',   wasmTarget: 'x86_64-apple-darwin'      },
  'macos-arm64':   { name: 'macOS Apple Silicon', bits: 64, family: 'arm',  platform: 'macos',   wasmTarget: 'aarch64-apple-darwin'     },
  'windows-x64':   { name: 'Windows x64',         bits: 64, family: 'x86',  platform: 'windows', wasmTarget: 'x86_64-pc-windows-msvc'   },
  'windows-x86':   { name: 'Windows x86',         bits: 32, family: 'x86',  platform: 'windows', wasmTarget: 'i686-pc-windows-msvc'     },
  'windows-arm64': { name: 'Windows ARM64',       bits: 64, family: 'arm',  platform: 'windows', wasmTarget: 'aarch64-pc-windows-msvc'  },
};

const PLATFORM_GROUPS = {
  web:     ['wasm32', 'wasm64'],
  mobile:  ['android-arm64', 'android-arm32', 'ios-arm64', 'arm64', 'arm32'],
  desktop: ['x86_64', 'x86_32', 'macos-x86_64', 'macos-arm64', 'windows-x64', 'windows-x86', 'windows-arm64'],
  server:  ['x86_64', 'arm64', 'riscv64'],
  all:     Object.keys(ARCH_TARGETS),
};

function detectCurrentArch() {
  const arch = process.arch;
  const plat = process.platform;
  if (plat === 'darwin' && arch === 'arm64') return 'macos-arm64';
  if (plat === 'darwin' && arch === 'x64')   return 'macos-x86_64';
  if (plat === 'win32'  && arch === 'x64')   return 'windows-x64';
  if (plat === 'win32'  && arch === 'ia32')  return 'windows-x86';
  if (plat === 'win32'  && arch === 'arm64') return 'windows-arm64';
  if (arch === 'x64')    return 'x86_64';
  if (arch === 'ia32')   return 'x86_32';
  if (arch === 'arm64')  return 'arm64';
  if (arch === 'arm')    return 'arm32';
  return 'wasm32';
}

class ArchCompiler {
  constructor(arch) {
    this.arch   = arch;
    this.target = ARCH_TARGETS[arch];
    if (!this.target) throw new Error(`Unknown architecture: ${arch}. Valid: ${Object.keys(ARCH_TARGETS).join(', ')}`);
  }

  get bits()     { return this.target.bits; }
  get family()   { return this.target.family; }
  get platform() { return this.target.platform; }

  getPointerType() {
    return this.bits === 64 ? 'i64' : 'i32';
  }

  generateHeader(moduleName) {
    return [
      `;; NTL Native Compilation Target`,
      `;; Architecture: ${this.target.name}`,
      `;; WASM Target Triple: ${this.target.wasmTarget}`,
      `;; Generated by NTL v3.0`,
      ``,
      `(module`,
      `  ;; Memory: 64 pages = 4MB initial`,
      `  (memory (export "memory") 64 1000)`,
      `  (global $ptr (mut ${this.getPointerType()}) (${this.getPointerType()}.const 65536))`,
      ``,
    ].join('\n');
  }

  generateMalloc() {
    const pt = this.getPointerType();
    return [
      `  ;; Simple bump allocator`,
      `  (func $malloc (export "malloc") (param $size ${pt}) (result ${pt})`,
      `    (local $ptr ${pt})`,
      `    (local.set $ptr (global.get $ptr))`,
      `    (global.set $ptr (${pt}.add (global.get $ptr) (local.get $size)))`,
      `    (local.get $ptr)`,
      `  )`,
      ``
    ].join('\n');
  }

  generatePrint() {
    return [
      `  ;; print_i32: prints integer (host call)`,
      `  (import "ntl" "print_i32" (func $print_i32 (param i32)))`,
      `  ;; print_f64: prints float (host call)`,
      `  (import "ntl" "print_f64" (func $print_f64 (param f64)))`,
      `  ;; print_str: prints string from memory (host call)`,
      `  (import "ntl" "print_str" (func $print_str (param i32 i32)))`,
      ``
    ].join('\n');
  }

  compileFunction(name, params, returnType, bodyWAT) {
    const paramStr  = params.map(p => `(param $${p.name} ${p.type})`).join(' ');
    const resultStr = returnType ? `(result ${returnType})` : '';
    return [
      `  (func $${name} (export "${name}") ${paramStr} ${resultStr}`,
      bodyWAT.split('\n').map(l => '    ' + l).join('\n'),
      `  )`,
      ``
    ].join('\n');
  }

  compileArithmetic(op, type) {
    const t = type || (this.bits === 64 ? 'f64' : 'f32');
    const ops = { '+': 'add', '-': 'sub', '*': 'mul', '/': 'div', '%': 'rem_s' };
    return `${t}.${ops[op] || 'add'}`;
  }

  generateFooter() {
    return `)\n`;
  }

  generateFunctionTable(functions) {
    const refs = functions.map(f => `    (elem (i32.const 0) $${f})`).join('\n');
    return [
      `  (table ${functions.length} funcref)`,
      refs,
      ``
    ].join('\n');
  }

  compileIntegerLoop(varName, limit, bodyWAT) {
    return [
      `  (local $${varName} i32)`,
      `  (local.set $${varName} (i32.const 0))`,
      `  (block $break`,
      `    (loop $loop`,
      `      (br_if $break (i32.ge_s (local.get $${varName}) (i32.const ${limit})))`,
      bodyWAT.split('\n').map(l => '      ' + l).join('\n'),
      `      (local.set $${varName} (i32.add (local.get $${varName}) (i32.const 1)))`,
      `      (br $loop)`,
      `    )`,
      `  )`,
    ].join('\n');
  }

  formatReport() {
    const t = this.target;
    return [
      `  Target Architecture Report`,
      `  ${'─'.repeat(40)}`,
      `  Name:      ${t.name}`,
      `  Bits:      ${t.bits}`,
      `  Family:    ${t.family}`,
      `  Platform:  ${t.platform}`,
      `  Triple:    ${t.wasmTarget}`,
      `  Pointer:   ${this.getPointerType()}`,
    ].join('\n');
  }
}

function resolveArchTargets(archStr) {
  if (!archStr) return [detectCurrentArch()];
  const targets = [];
  for (const part of archStr.split(',')) {
    const t = part.trim();
    if (PLATFORM_GROUPS[t]) {
      targets.push(...PLATFORM_GROUPS[t]);
    } else if (ARCH_TARGETS[t]) {
      targets.push(t);
    } else {
      throw new Error(`Unknown arch or group: "${t}". Valid: ${Object.keys(ARCH_TARGETS).concat(Object.keys(PLATFORM_GROUPS)).join(', ')}`);
    }
  }
  return [...new Set(targets)];
}

module.exports = { ARCH_TARGETS, PLATFORM_GROUPS, ArchCompiler, detectCurrentArch, resolveArchTargets };
